# Generated by Django 3.0.9 on 2020-11-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
