# Generated by Django 3.0.9 on 2020-11-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20201118_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
