# Generated by Django 3.0.9 on 2020-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20201118_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
