# Generated by Django 3.0.9 on 2020-11-18 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_feeditem_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='like',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='like',
            field=models.ManyToManyField(related_name='likepost', to=settings.AUTH_USER_MODEL),
        ),
    ]
