# Generated by Django 3.0.9 on 2020-11-18 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0006_auto_20201117_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='like',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
