# Generated by Django 3.0.9 on 2020-11-18 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0008_auto_20201117_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='likes',
            field=models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
