# Generated by Django 3.0.9 on 2020-11-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20201117_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='likes',
        ),
    ]
