# Generated by Django 3.0.9 on 2020-11-18 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0011_auto_20201117_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='user_likes',
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
