# Generated by Django 3.0.9 on 2020-12-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20201205_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='profile_picture',
            field=models.ImageField(blank=True, default='yoda.png', null=True, upload_to=''),
        ),
    ]
