# Generated by Django 3.0.9 on 2020-12-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20201215_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userselection',
            name='team_selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Category'),
        ),
    ]
