# Generated by Django 3.0.9 on 2020-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20201215_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselection',
            name='team_selected',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
