# Generated by Django 3.0.9 on 2020-12-01 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=30)),
                ('league_id', models.CharField(max_length=10)),
                ('league_password', models.CharField(max_length=20)),
                ('league_commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner', to=settings.AUTH_USER_MODEL)),
                ('league_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
