# Generated by Django 3.0.9 on 2020-12-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201205_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='yoda.png', null=True, upload_to=''),
        ),
    ]
