# Generated by Django 3.0.9 on 2020-12-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201205_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_password',
        ),
    ]
