# Generated by Django 3.0.9 on 2020-12-14 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201205_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_password',
        ),
        migrations.RemoveField(
            model_name='league',
            name='league_members',
        ),
        migrations.AddField(
            model_name='league',
            name='league_members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
