# Generated by Django 3.0.9 on 2020-12-14 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20201214_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
