# Generated by Django 3.0.9 on 2020-12-14 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20201214_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_members',
        ),
        migrations.AddField(
            model_name='league',
            name='league_members',
            field=models.ManyToManyField(null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
