# Generated by Django 3.0.9 on 2020-12-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201214_1349'),
        ('core', '0008_auto_20201214_1424'),
    ]

    operations = [
    ]
