# Generated by Django 3.0.9 on 2020-12-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('away_score', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('current_period', models.IntegerField()),
                ('time_remaining', models.CharField(max_length=255)),
                ('home_team_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('away_team_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('game_date', models.CharField(max_length=255)),
            ],
        ),
    ]
