# Generated by Django 3.0.9 on 2020-12-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='summary',
            new_name='home_team',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
