# Generated by Django 3.0.9 on 2020-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201207_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_perriod',
            new_name='current_period',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
