# Generated by Django 3.0.9 on 2020-12-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201207_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
